### ISSUE TITLE
2017-02-08 Meeting Notes

### ISSUE THREAD

**Issue by ahunker** [ahunker/Hamilton-Project#2]
We met for about half an hour and discussed what we're specifically going to be marking up in our files and how we'll divide the workload. @bsf15 Will be tagging repeated phrases and I'll be looking at people names, specifically who is speaking the most, who is mentioned the most, and maybe who each character talks about the most. We would also like to make a timeline based on the musical itself. I will be creating a codebook based on TEI so we can start converting the text files into XML. We've agreed that I will mark up Act One and Bri will mark up Act Two structurally. From there, we'll go back and grab the information we need individually. 

@RJP43 @ebeshero

**Comment by RJP43** [comment]
@ahunker @bsf15 Here are some links to what we had discussed before class:

TEI performance text module - http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DR.html  

Some projects from our sister course at Pitt-Oakland that dealt with marking up songs/music (not all, if any, of these use TEI; however, they may be interesting to look at for other ideas regarding markup):

- [Musicality of Phrase: An Analysis of Five Songs By Andrew Lloyd Webber](http://music.obdurodon.org/)
- [Discovering Protest Music: Can We Define It?](http://protest.obdurodon.org/resources.php#xml_data)

- [Turkish Rock Music](http://turkish.obdurodon.org/)  

Section from the TEI discussing markup of words and phrases - http://www.tei-c.org/release/doc/tei-p5-doc/en/html/AI.html#AILC

**Hope this helps! Great work so far ladies!**
