### ISSUE TITLE
JavaScript for About Page

### ISSUE THREAD

**Issue by ebeshero** [ahunker/Hamilton-Project#25]
This needs some work. See two versions that @ahunker and I worked on. We need to toggle off an on based on matching the @id of the button to the @id on the div.

**Comment by ebeshero** [comment]
@ahunker I've just repaired the JavaScript so it's working as you'd planned!
(It's in this commit: With this commit https://github.com/ahunker/Hamilton-Project/commit/ca5adc23a9c7971f274370c8dfb17fad6d25272a ,  ) I made some very small changes to the `@id` values in [the HTML](https://github.com/ahunker/Hamilton-Project/blob/master/Hamilton_WebPage/about.html) to make [the JavaScript](https://github.com/ahunker/Hamilton-Project/blob/master/Hamilton_WebPage/about.js) as clear and simple as possible.  

By the way, this was MUCH simpler than we thought before the dinner hour! :-) But we *did* need to use JavaScript's "this" syntax, to match up the id of a button to an id of a div. And we just needed to write a third function to hide *all* the divs BEFORE displaying the selected div. 
@RJP43

**Comment by ahunker** [comment]
I updated the site, so this is now firing online. Thank you!
