### ISSUE TITLE
XSLT for Personography Table

### ISSUE THREAD

**Issue by ebeshero** [ahunker/Hamilton-Project#28]
@ahunker I think I repaired the problem we were seeing earlier today with the Personography Table columns, in this commit: https://github.com/ahunker/Hamilton-Project/commit/e17a41cda571bcaed20158c300e5902373768d87

Take a look and run the output and tell me if it makes sense and looks like you're catching everything (and not too much of anything). 
@RJP43

**Comment by ahunker** [comment]
I've got it up on the site now. Check it out [here](http://hamilton.newtfire.org/vis_Network.html).
