### ISSUE TITLE
Faulty Who Attributes

### ISSUE THREAD

**Issue by bsf15** [ahunker/Hamilton-Project#7]
@ahunker @ebeshero 
I went through the song files and I found some of issues relating to the who attributes:

In Act_One, in the song "Satisfied", there is a who attribute called: #recording
I don't know if we still want to change all the misc who attributes to #ensemble or not, but I did notice that among all the who attributes, one random #recording seemed out of place, despite the fact it is marking up a speaker labelled as a recording or some sort.

The bigger issues were these ones in Act_Two though.

In "Take a Break", there are two cases were Hamilton's who attribute lacks the hashtag, so we have only: hamilton 

In "Cabinet Battle 1", Washington lacks a hashtag on his who attribute, which results in:
washington

"Who Lives, Who Dies, Who Tells Your Story" there is a who attribute that only has a hashtag instead of properly having the who attribute labeling #company. 

And in "Schuyler Defeated" contains the philip attribute that needs to be philipH.

I know in the XQuery, when looking at distinct speakers I also saw: a blank space. I was unable to find that though. 

This is totally unrelated to the who attributes, but I also noticed that in "One Last Time", in the first line of the song from Hamilton, the persName reference seems to be cutting short and is only grabbing Mr.Presiden as opposed to Mr.President.  Also, I was thinking of fixing the title for Cabinet Battle 1, so it would not be in all caps to look  more uniform with the rest of the songs.

I didn't want to go in and actually change anything within exist right away in case I messed up something for the homework, and I was going to attempt to push the changes/fixes I did make in the files, but it looked like there was a chance of me accidentally deleting song 21 in Act One. Since, I know we are currently having issues with that song, I didn't want to mess things up with a minor push.

**Comment by ahunker** [comment]
If you found the issues, you should push the changes. In what way may you accidentally delete song 21 in Act One? If it's because you don't have the song, that should be an issue. You should first pull in any changes then push your changes.

**Comment by bsf15** [comment]
Yeah, I've pulled in changes and whenever I look into the files, song 21 isn't there for some reasons. I can try to look on my computer tonight when I get home instead of a lab computer, but at least here whenever I pull in everything I get no xml version of song 21, no txt version, and there is no webpage/html version.
Whenever I go to add the fixed files, it shows this as changes to be commited:
  deleted:    Converted_Texts/Act_One/HTML/21_WhatComesNext?.html
        deleted:    Converted_Texts/Act_One/TEXT/21_WhatComesNext?.txt
        deleted:    Converted_Texts/Act_One/XML/21_WhatComesNext?.xml
        modified:   Converted_Texts/Act_Two/XML/02_CabinetBattle1.xml
        modified:   Converted_Texts/Act_Two/XML/03_TakeABreak.xml
        modified:   Converted_Texts/Act_Two/XML/09_OneLastTime.xml
        modified:   Converted_Texts/Act_Two/XML/23_WhoLivesWhoDiesWhoTellsYourStory.xml
        deleted:    Hamilton_WebPage/21_WhatComesNext?.html
I don't know if this is okay, and if I should just go through with the push or not. Again, I'll see if maybe the issue is due to the lab computer and I'll try pulling in and pushing at home to see if I can avoid the deleted portion of the commit.

**Comment by ebeshero** [comment]
@ahunker Bri and I noticed after class on Monday that somehow the classroom lab computer didn't pull in Song 21 when she cloned the repo (or we didn't see it), but I definitely had it on my computer (and we made sure it's in the eXist hamilton repo, too). I'm not sure what was going on, but Bri, I hope you have it now? @bsf15

**Comment by ebeshero** [comment]
@bsf15 Sorry--I was a little slow on the uptake and just realized the danger you were explaining with going to add the repaired files. Of course you don't want to commit to deleting Song 21 (and we don't know how that happened.) If you are seeing this on your home computer, here's a simple workaround: Try downloading Song 21's XML, HTML, and TXT from the cloud GitHub (from the browser) and drop them into the appropriate folders. Check the git status then, and I bet all will be okay. It's a sort of manual workaround but should ensure your files are where they are supposed to be. I suspect there was a merge conflict somehow that resolved in a strange way--you didn't have song 21 when you made the changes to commit to the repo(?) Git should resolve all that, but this way you can just make sure you've *added* that song yourself. 

I do have all the files here locally on my Mac, and song 21 is in eXist, too now.

**Comment by ahunker** [comment]
Did you manage to fix the merge conflict Bri?

**Comment by bsf15** [comment]
@ahunker  The issue with the What Comes Next song not properly pulling in was due to the question mark at the end, so we changed the file name so it works.
